name: 'compratech_dw'
version: '1.0.0'
config-version: 2

profile: 'compratech_dw'

model-paths: ["models"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  compratech_dw:
    staging:
      +materialized: view

    marts:
      +materialized: table

snapshots:
  compratech_dw:
    +target_schema: snapshots